services:
  es01:
    image: elasticsearch:9.1.0
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    expose:
      - '9200'
      - '9300'
    deploy:
      resources:
        limits:
          memory: 3G

  backend: &backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=template-method
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - '3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
